### ISSUE TITLE
Some type of question cause the asking process to stop silently

### ISSUE THREAD

**Issue by MrSimsure** [aelliixx/cpp-inquirer#1]
Hello, first of all, this library is really wonderful, i was looking exactly for something this simple and yet powerful to build my command line tools.
But i'm having some problems when using different type of questions, specifically if i use the 'text' type before every other question, everything works as excepted, but if use any of the other type before the 'text' one, the program stop silently without asking any question at all.
I'm pretty new to C++, so i don't know if this could be something wrong with my setup or the library itself.
Here an example of what i'm talking about, i pretty much just use the same code form your examples.

This way it works, and every question is asked one after another
``` cpp
auto inquirer = alx::Inquirer("");
		
inquirer.add_question({ "query", "What do you want to do?" });
inquirer.add_question({ "birthday", "Is this for a birthday?", alx::Type::yesNo });
inquirer.add_question({ "candles", "How many candles do you want?", alx::Type::integer });
inquirer.add_question({ "delivery", "Is this for delivery?", alx::Type::confirm });
inquirer.add_question({ "type", "What kind of a cake would you like?",
		    std::vector<std::string>{ "Chocolate", "Ice-cream", "Cheesecake", "Red velvet" }});

inquirer.ask();
 ```

But just doing this cause my problem, any other type of question does not work if a 'text' question is not asked before, and nothing come out of the terminal
``` cpp
auto inquirer = alx::Inquirer("");
		
//inquirer.add_question({ "query", "What do you want to do?" });
inquirer.add_question({ "birthday", "Is this for a birthday?", alx::Type::yesNo });
inquirer.add_question({ "candles", "How many candles do you want?", alx::Type::integer });
inquirer.add_question({ "delivery", "Is this for delivery?", alx::Type::confirm });
inquirer.add_question({ "type", "What kind of a cake would you like?",
		    std::vector<std::string>{ "Chocolate", "Ice-cream", "Cheesecake", "Red velvet" }});

inquirer.ask();
 ```
What could be the problem?

**Comment by aelliixx** [comment]
Hey, thanks for the issue!
I tried replicating your problem on two different machines, however, I couldn't get it to not work.

Compiled with gcc on C++11, 14, 17, and 20, no issues as far as I could find.

Could you perhaps provide more details about what platform you're using, which compiler, and which C++ version?

In case it is a problem with the library, if you feel like delving into it and you know how to use the debugger, you could put a breakpoint on Inquirer::ask() and step through it to see why the function falls through. I'm more than happy to accept pull requests, but if not, some more details on your setup would be great so I could fix it myself.

Cheers!

**Comment by aelliixx** [comment]
Closing due to not being able to replicate the issue and no response from the issue author

**Comment by MrSimsure** [comment]
Sorry for the disappear, i didn't had the time to investigate further on the problem, but after coming back and making some testing, i found out that the problem appear to arise when the project is compiled using MSVC, the visual studio compiler.
Compiling with gcc or clang seems to work as intended.
I'm gonna make some other test to find out what doesn't work with msvc.

**Comment by aelliixx** [comment]
I see. I never intended this library to work on windows, but perhaps that's a worthy idea nonetheless.

I don't have access to msvc myself, being on Linux, so the best I could do is make it compatible with mingw. Otherwise, I'm more than happy to take pull requests if you do find and fix the issue yourself :)

**Comment by MrSimsure** [comment]
Found it!
Apparently it was the _union_ type inside the Question class to cause the problem.
`union
{
  std::vector<std::string> options;
  std::string regex;
};`

if i remove the union so that options and regex are direct property of the class it works, don't know if this is a bug in MSVC or it is supposed to work differently.
From what i understand _union_ is meant to reduce memory consumption by only making space for a specific property and not for both based on the constructor.
I already adapted the library to work on windows to suits my needs, so i can totally make a pull request for that, but for this specific MSVC problem what can be the best solution to fix it?

The simpler one would be to remove the union type, and trade memory for compatibility, it will compile under every main compiler this way, or maybe a #DEFINE rule to don't use the union only when the compiler is msvc, what do you think?

**Comment by aelliixx** [comment]
Doh! Shouldn't use C-style unions anyway!
I think you're right, I don't expect the options vector to be terribly large and we don't have to worry so much about the memory these days anyway. So yeah, a quick fix would be moving those union members out of the union.
Long term we could use `std::variant` if we're keen on reducing the memory usage.

I'm happy to accept the patch if you do a PR :)
