### ISSUE TITLE
Ctrl + C get eaten by getchar in options question.

### ISSUE THREAD

**Issue by jaanonim** [aelliixx/cpp-inquirer#3]
Ctrl+C don't interrupt program when presed while inquirer waits for selection from options question.

**Comment by aelliixx** [comment]
Hey, thanks for the issue! Could you provide some details about what compiler, platform, and options you use before I try to reproduce it?

**Comment by jaanonim** [comment]
Setup to reproduce:
- OS: Linux
- cmake: `3.28.3`
- make: `4.3`

1. Clone this repo.
2. Build `cmake --build ./cmake-build-debug --target cpp_inquirer -j 10`
3. Run `./cmake-build-debug/cpp_inquirer `

On this steps presing Ctrl+C does nothing.
![image](https://github.com/aelliixx/cpp-inquirer/assets/28810058/56c7c42b-cf42-480c-a884-ee8bbf297e87)
![image](https://github.com/aelliixx/cpp-inquirer/assets/28810058/e8624c1f-7171-4377-bf66-94ea34df3672)

**Comment by aelliixx** [comment]
I'll have a look. Cheers!

**Comment by aelliixx** [comment]
Should be fixed in the latest push. I haven't tested it on Windows, so not sure if it works there.
Feel free to reopen the issue if the issue persists :)

**Comment by jaanonim** [comment]
Thanks for so quick respones. It's working now (on Linux).  <3
