### ISSUE TITLE
When using a question with an option to select, the question is getting printed every time up/down keyboard is getting pressed

### ISSUE THREAD

**Issue by kyrylolvov** [aelliixx/cpp-inquirer#4]
https://github.com/aelliixx/cpp-inquirer/assets/70720713/3300c751-2856-44e4-befc-dcf7ca7bfb90

**Comment by aelliixx** [comment]
Hi, could you leave your compiler/OS you're using? Thank you!

**Comment by kyrylolvov** [comment]
@aelliixx 
Ubuntu 22.04.3 LTS
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by aelliixx** [comment]
Thanks! I'll have a look as soon as I can though it might be next week. Feel free to investigate yourself, I accept PRs :)

**Comment by kyrylolvov** [comment]
@aelliixx Just tried to use the example code from https://github.com/aelliixx/cpp-inquirer/blob/main/src/main.cpp. This issue doesnt appear, so I would assume it only appears if you dont have any question being asked before it.

**Comment by aelliixx** [comment]
Could you post the code that broke for you?

**Comment by kyrylolvov** [comment]
@aelliixx Hello! Somehow I changed something in the code, so this issue doesn't appear now, so I would assume I coded something wrong. Sorry for creating an issue
